### ISSUE TITLE
Create ViewableEntity

### ISSUE THREAD

**Issue by Glebanister** [PlatformerTeam/mad#44]
- [x] Fields position, z_index
- [x] move(FVec2d) (depends on #31)
- [x] get_image_position(): FVec2d
- [x] set_image_position(FVec2d)
- [x] appear(EventDispatcher &) - sends PositionalAppearance to EventDispatcher (depends on #32)
- [x] Implement `accept(Event)` for parent class Entity, which assumes that intent has lambda and applies it to self (depends on #40 on the LabmdaIntent part)
